### ISSUE TITLE
How to use maxima-syntax-highligting

### ISSUE THREAD

**Issue by PepeRosell** [nicoewok/maxima-syntax-highlighting#1]
Hello people.
My name is Jose and I am learning maxima and LaTeX for my work as a mathematician. I am a a beginner. 
In my University - Universidad de Murcia, Spain- we work LaTeX files within maxima language; we can do it because of a package created by our Profesor Jose Manuel Mira, maxiplot, which provides a .mac file and this file compiles, at the same time, as the LaTeX one, but in maxima. 
The question is: how can I use your extension to compile the Mac file in vscode? Thank you

**Comment by nicoewok** [comment]
Hello Jose!
This extensions purpose is only to highlight different parts of the syntax in distinct groups. If you don't have this extension it just looks like a plain text file.
If you want to compile/execute your code you will still have to do it in the terminal. This extension unfortunately can't help you with compilation.
It's also not a planned feature.
So for compilation you'll have to stick to your professor's instructions for now.

But as this is opensource, feel free to give a compilation feature a try if you want to!

**Comment by PepeRosell** [comment]
Tanks Nicoewok, I'll try it if I can learn how to do it.
