### ISSUE TITLE
single quotes

### ISSUE THREAD

**Issue by barton-willis** [nicoewok/maxima-syntax-highlighting#2]
Hi, 

Thanks for this contribution.   One thing that I noticed:  single quotes mess up parenthesis matching. In an editor window, try

~~~
(load('lrats), load('simplifying), load('integer_sequence));
~~~

Thanks.  (If I posted this multiple times, I apologize. But I thought I posted it once, but vanished--on the chance that I didn't submit, here it is again.)

Barton Willis
Maxima Developer

**Comment by nicoewok** [comment]
Hi,
sorry for the late response. If I understood the issue correctly it has to do with my support of single-quoted strings. As strings are only double-quoted in maxima I have now removed this feature which fixed your example above. As you are a Maxima Developer please have a look at the newest version to verify.
Thanks for the contribution!

**Comment by barton-willis** [comment]
I've tested your new version--it resolves the issue that I reported. Thanks for taking care of this and thanks for your contribution to Maxima.
